spring:
  cloud:
    gateway:
      routes:
        - id: CRM-service
          uri: lb://CRM-service
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
            - JwtHeaderFilter
        - id: SSO-service
          uri: lb://SSO-service
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1

const:
  auth:
    introspection-uri: http://SSO-service/auth/introspection

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8080
