spring:
  cloud:
    gateway:
      routes:
        - id: CRM-service
          uri: lb://CRM-service
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
            - JwtHeaderFilter

const:
  auth:
    introspection-uri:

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8080
