spring:
  datasource:
    url: jdbc:h2:mem:cdr-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
const:
  numberOfGenerationThreads: 5
  numberOfRecordsInCDR: 10


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8082
