spring:
  datasource:
    url: jdbc:h2:mem:roaming-aggregator-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: false


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8082
