spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/brt-db
    username: postgres
    password: postgres

const:
  hrs-service:
    BASE_URL: http://localhost:8084
  rabbitmq:
    CDR_QUEUE_NAME: cdr.queue
    CDR_EXCHANGE_NAME: cdr.direct
    CDR_ROUTING_KEY: cdr.created

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8081