spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://brt-db:5432/brt-db
    username: postgres
    password: postgres

const:
  hrs-service:
    BASE_URL: http://HRS-service
  rabbitmq:
    cdr:
      CDR_QUEUE_NAME: cdr.queue
      CDR_EXCHANGE_NAME: cdr.direct
      CDR_ROUTING_KEY: cdr.created
    bills:
      BILLS_QUEUE_NAME: bills.queue
      BILLS_EXCHANGE_NAME: bills.exchange
      BILLS_ROUTING_KEY: bills.created
    tariffication:
      CALL_USAGE_QUEUE_NAME: tariffication.usage.call.queue
      CALL_USAGE_ROUTING_KEY: tariffication.usage.call
      TARIFFICATION_EXCHANGE_NAME: tariffication.exchange
    subscriber:
      SUBSCRIBER_CREATED_QUEUE_NAME: subscriber.created.queue
      SUBSCRIBER_CREATED_EXCHANGE_NAME: subscriber.created.exchange
      SUBSCRIBER_CREATED_ROUTING_KEY: subscriber.created
    dead-letter:
      DEAD_LETTER_QUEUE_POSTFIX: .dlq
      DEAD_LETTER_EXCHANGE_POSTFIX: .dlx
      DEAD_LETTER_ROUTING_KEY_POSTFIX: .dlr

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 2

management:
  endpoints:
    web:
      exposure:
        include: "health,info,eurekaRegistration"
  endpoint:
    health:
      show-details: always

server:
  port: 8081