spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hrs-db:5432/hrs-db
    username: postgres
    password: postgres

const:
  rabbitmq:
    bills:
      BILLS_QUEUE_NAME: bills.queue
      BILLS_EXCHANGE_NAME: bills.exchange
      BILLS_ROUTING_KEY: bills.created
    tariffication:
      CALL_USAGE_QUEUE_NAME: tariffication.usage.call.queue
      CALL_USAGE_ROUTING_KEY: tariffication.usage.call
      TARIFFICATION_EXCHANGE_NAME: tariffication.exchange
    dead-letter:
      DEAD_LETTER_QUEUE_POSTFIX: .dlq
      DEAD_LETTER_EXCHANGE_POSTFIX: .dlx
      DEAD_LETTER_ROUTING_KEY_POSTFIX: .dlr


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 2

management: # Configure Actuator
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics,eurekaRegistration" # Expose health, info and custom health indicator
  endpoint:
    health:
      show-details: always # Show detailed health information
      # Optional: if you want your custom health indicator to be part of the main health status by default
      # group:
      #   readiness:
      #     include: "eurekaRegistration,db,diskSpace,ping" # Add other relevant health indicators

server:
  port: 8084