spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/hrs-db
    username: postgres
    password: postgres

const:
  rabbitmq:
    bills:
      BILLS_QUEUE_NAME: bills.queue
      BILLS_EXCHANGE_NAME: bills.exchange
      BILLS_ROUTING_KEY: bills.created
    tariffication:
      CALL_USAGE_QUEUE_NAME: tariffication.usage.call.queue
      CALL_USAGE_ROUTING_KEY: tariffication.usage.call.*
      TARIFFICATION_EXCHANGE_NAME: tariffication.exchange


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8084