spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://sso-db:5432/sso-db
    username: postgres
    password: postgres

server:
  port: 8765