spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/sso-db
    username: postgres
    password: postgres

const:
  rabbitmq:
    subscriber:
      SUBSCRIBER_CREATED_QUEUE_NAME: subscriber.created.queue
      SUBSCRIBER_CREATED_EXCHANGE_NAME: subscriber.created.exchange
      SUBSCRIBER_CREATED_ROUTING_KEY: subscriber.created
    dead-letter:
      DEAD_LETTER_QUEUE_POSTFIX: .dlq
      DEAD_LETTER_EXCHANGE_POSTFIX: .dlx
      DEAD_LETTER_ROUTING_KEY_POSTFIX: .dlr

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8765