spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://sso-db:5432/sso-db
    username: postgres
    password: postgres

const:
  rabbitmq:
    subscriber:
      SUBSCRIBER_CREATED_QUEUE_NAME: subscriber.created.queue
      SUBSCRIBER_CREATED_EXCHANGE_NAME: subscriber.created.exchange
      SUBSCRIBER_CREATED_ROUTING_KEY: subscriber.created

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true


server:
  port: 8765